### ISSUE TITLE
Documentation: Monsters without an alignment are not included in the results

### ISSUE THREAD

**Issue by crimsonknave** [MrPrimate/ddb-proxy#10]
:wave: I ran into a very weird issue and thought it might be good to have a note somewhere in the docs.

I was unable to import any monster I created that didn't have an alignment set. It simply wouldn't show up, but as soon as I set an alignment it was there. Nothing in dndbeyond shows an error when you have `---` as your alignment, and it displays fine on the site, but it appears that the dndbeyond API doesn't include those monsters in the results.

**Comment by MrPrimate** [comment]
Do you have a link to the monster you can share (here or via discord?)

**Comment by crimsonknave** [comment]
I can no longer reproduce this. Before I could recreate this by creating a new monster from scratch and setting all the required fields (which didn't include alignment) and saving. That monster would not import and it would not show up in the logs of the proxy either. I did the same thing just now and it flowed through just fine.

I did now just notice that it appears to import deleted monsters too, which is not what I want, but, not sure there's much you can do about that since it'll just be what the API returns.
