### ISSUE TITLE
Cors origin configurable via environmental variable.

### ISSUE THREAD

**Issue by astandley** [MrPrimate/ddb-proxy#16]
It would be nice to be able to modify the cors configuration to set the allowed origins via an environmental variable. 
Even following the README to run the docker image locally will result in CORS errors as the origin `http://localhost:8080` does not match the server's expected `http://localhost:3000`. 

I might be missing something but I can't image how someone is running that image with a cloud provider without manually modifying the index.js as it is. Seems like it would be nice if you could use things out the box.

**Comment by astandley** [comment]
(All that said, you are a legend for OS all of these tools. Would love to help out in all the free time you're saving that would have been spent creating Foundry scenes for pre-written adventures!)

**Comment by MrPrimate** [comment]
@astandley you should run it behind a proxy such as Caddy or ngnix. This should allow you to provide appropriate CORS requirements. That said I haven't had any problems running this locally, so it could be that something is configured incorrectly?

What did you set `game.settings.set("ddb-importer", "api-endpoint", xxx)` to?

**Comment by airstandley** [comment]
Ah, right if they're running it behind behind proxy then the proxy is correcting the origin on the proxied request to the value the service expects.

I set it to "http://localhost:8080" since I had followed the docker instructions and mapped port 3000 to 8080. Fixing the mapping to 3000:3000 and using "http://localhost:3000" obviously works fine.

**Comment by airstandley** [comment]
(Can't find the close button on mobile, but this can definitely be closed as you are right that running it behind a proxy resolves the issue for non-local, and there's only issues running local if using docker with a different port mapping)

Thanks for the reply!

**Comment by MrPrimate** [comment]
I'll update the instructions to remove the mapping to make sure no one else runs into it

**Comment by mivalsten** [comment]
Hey, as a creator of docker instruction, I'm sorry for this issue. I have opened a PR with fixed wording as well as mention of prebuilt image.
