### ISSUE TITLE
Cannot read properties of undefined (reading 'classOptions')

### ISSUE THREAD

**Issue by julianpoy** [MrPrimate/ddb-proxy#18]
Seeing the following error when using the ddb-proxy, but not when using the hosted version.

![image](https://user-images.githubusercontent.com/7751154/162636165-e5b30ce8-b3be-4d56-9a24-68ec23351b12.png)

**Comment by MrPrimate** [comment]
Is your cobalt cookie valid?

**Comment by julianpoy** [comment]
It is, yep. Works fine the moment I disable the proxy.

**Comment by MrPrimate** [comment]
If you go to Settings -> DDB Importer -> Core Setup -> Check Cobalt Cookie, does it work? (It will still try to import a character if the cookie has expired/is incorrect), this setting should show us if it is working.

**Comment by julianpoy** [comment]
Yep

**Comment by nielsk** [comment]
I have the same problem

**Comment by nielsk** [comment]
Cobalt Cookie is working

**Comment by MrPrimate** [comment]
Can you provide a character URL?

**Comment by nielsk** [comment]
Sure:

https://www.dndbeyond.com/characters/72504563

**Comment by MrPrimate** [comment]
Please can you try the latest code/v0.0.18

**Comment by nielsk** [comment]
That worked for me 👍 
Thanks a lot
