### ISSUE TITLE
Grafana listens on port 3000 in Linux

### ISSUE THREAD

**Issue by doonze** [MrPrimate/ddb-proxy#28]
Just FYI, in case anyone else runs into this. Grafana listens on tcp6 port 3000, and conflicts with the DDB-proxy instance also trying to listen on port 3000. Took some doing to find what was on that port, but once I did, the fix was simple. I took down Grafana. I throw this out there as Grafana is a pretty popular program. I don't see a way to change the port in DDB-proxy. Grafana might have a way, but it was a test project I abandoned a few years ago so just disabled it. 

Just putting this out there on the interwebs.

**Comment by MrPrimate** [comment]
This is already an option using the `PORT` env var https://github.com/MrPrimate/ddb-proxy/blob/main/index.js#L18

**Comment by doonze** [comment]
Oh ok. I looked for config info in every file but index! Thanks, great to know.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mivalsten** [comment]
If possible, don't run this directly from OS, and instead use docker. You can just do:
```sh
docker run -p [port-you-want]:3000 ghcr.io/mrprimate/ddb-proxy:latest
```
