### ISSUE TITLE
Mucher stops working when using SSL for Foundry

### ISSUE THREAD

**Issue by raymondtrueman** [MrPrimate/ddb-proxy#30]
The Monster Munch feature was working fine until I switched FoundryVTT to use SSL. AFter that it just does not even bring up the Core Config for the importer. When I disable using a custom proxy then it works again (but obviously only with Patreon support). So I am thinking that it probably fails because ddb-proxy is not runningon SSL. Is there a way to provide a certificate and key to ddb-proxy so it can run on SSL?

There might however be another bug causing this issue but that is the only thing that changed - Foundry was switched to SSL

**Comment by MrPrimate** [comment]
You need to run it behind a proxy like Nginx or Caddy. You shouldn't _really_ be running Foundry without these; node does not make a great secure proxy device. Configuring these applications is some of the excellent service I bring to my own proxy, and you can learn more about running them through articles on the Foundry website or the internet in general.
