### ISSUE TITLE
FoundryVTT D&D Beyond Character Import Failed

### ISSUE THREAD

**Issue by jfvandyk** [MrPrimate/ddb-proxy#6]
Hello,

Since a recent change between ddb-proxy and ddb-importer I believe sometime between late August was the last time it was working, and the 9th of September was when I first noticed it having an issuing importing the characters from D&DBeyond.

The error message received during the attempted character import from the Character sheet is:
- **Unknown error during character parsing: TypeError: Cannot read properties of undefined (reading 'map')**

Disabling the custom proxy allows the import to succeed.

Versions
ddb-proxy running with latest commit sha 390190a, commit date the 10th of September
ddb-importer v2.5.6
FoundryVTT v0.8.9

**Comment by MrPrimate** [comment]
Sorry! Fixed in the latest commit/v0.0.9

**Comment by jfvandyk** [comment]
No worries, thank-you.

Changes has resolved the issue.
