### ISSUE TITLE
DDB-Proxy v0.0.10 - Adventure Munch Monster Import Error

### ISSUE THREAD

**Issue by jfvandyk** [MrPrimate/ddb-proxy#9]
Hello,

Just looking into Adventure Munch, I am not certain if ddb-proxy is meant to be able to handle the Adventure Munch, in the event it should I get the following error:

_Failed to load resource: the server responded with a status of 404 () proxy/monsters/ids:1

DDB Importer | ERR > Error importing file slw.fvttadv SyntaxError: Unexpected token < in JSON at position 0
log @ main.js:1621_

This appears to be a problem with ddb-proxy, when I disable it, the import is successful.

Version of ddb-proxy: **0.0.10**

**Comment by MrPrimate** [comment]
Ah! Thanks for rhI still need to add in this functionality - as a work around do a full Monster Munch unto your DDB compendium first - this should bypass the monster/id call

**Comment by MrPrimate** [comment]
This is in the latest release of DDB Importer and DDB Proxy
